### ISSUE TITLE
배너

### ISSUE THREAD

**Issue by kimseungdeok** [NooChuHan/NooChuHan-Frontend-monorepo#9]
# Description
figma 에 배너 이미지를 스와이프 + 버튼 클릭시 슬라이드 기능을 추가,
최대한 util로 사용할수있게 imge input만 추가하면 재사용 할 수 있는 컴포넌트로

# To-do
- [ ] 비지니스 로직 test code 작성
- [ ] 비지니스 로직 구현
- [ ] 컴포넌트 레이아웃 구현
- [ ] 컴포넌트 디자인 구현

# ETC
라이브러리 없이 구현
